# Generated by Django 3.1.3 on 2022-01-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wideocollectorseader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producents',
            name='avatar',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='producents',
            name='banner',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='producents',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='producents',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producents',
            name='dir',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='producents',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producents',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producents',
            name='show_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='producents',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
