# Generated by Django 3.1.3 on 2022-03-23 15:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wideocollectorseader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLikess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('show_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('avatar', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('src', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('web_src', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('poster', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('country', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date_relesed', models.DateField(blank=True, null=True)),
                ('dir', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('web_dir', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('added', models.DateTimeField(auto_now=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('likes_count', models.IntegerField(default=0)),
                ('disLikes_count', models.IntegerField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('disLikes', models.ManyToManyField(blank=True, related_name='MovieDisLike', to='wideocollectorseader.DisLikess')),
                ('likes', models.ManyToManyField(blank=True, related_name='Movielikes', to='wideocollectorseader.Likes')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('added', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('banner', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('show_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('avatar', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('dir', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('web_dir', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('added', models.DateTimeField(auto_now=True)),
                ('years', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('number_of_sezons', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('likes_count', models.IntegerField(default=0)),
                ('disLikes_count', models.IntegerField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('show_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('weight', models.IntegerField(blank=True, default=0, null=True)),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
                ('ethnicity', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('hair_color', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('birth_place', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('dir', models.CharField(default='', max_length=200, null=True)),
                ('web_dir', models.CharField(default='', max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('likes_count', models.IntegerField(default=0)),
                ('disLikes_count', models.IntegerField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('movies_count', models.IntegerField(default=0)),
                ('disLikes', models.ManyToManyField(blank=True, related_name='StarDisLike', to='wideocollectorseader.DisLikess')),
                ('likes', models.ManyToManyField(blank=True, related_name='Starlikes', to='wideocollectorseader.Likes')),
                ('movies', models.ManyToManyField(blank=True, related_name='StarsMovies', to='wideocollectorseader.Movie')),
                ('ratings', models.ManyToManyField(blank=True, related_name='StarRating', to='wideocollectorseader.Rating')),
                ('series', models.ManyToManyField(blank=True, related_name='StarSerie', to='wideocollectorseader.Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='producents',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producents',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producents',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producents',
            name='banner',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producents',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producents',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='producents',
            name='dir',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producents',
            name='disLikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producents',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producents',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producents',
            name='show_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producents',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producents',
            name='web_dir',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producents',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producents',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movies', models.ManyToManyField(blank=True, related_name='Movies', to='wideocollectorseader.Movie')),
                ('producents', models.ManyToManyField(blank=True, related_name='Producents', to='wideocollectorseader.Producents')),
                ('series', models.ManyToManyField(blank=True, related_name='Serie', to='wideocollectorseader.Serie')),
                ('stars', models.ManyToManyField(blank=True, related_name='Stars', to='wideocollectorseader.Star')),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Starstags', to='wideocollectorseader.Tag'),
        ),
        migrations.AddField(
            model_name='star',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='StarViews', to='wideocollectorseader.Views'),
        ),
        migrations.AddField(
            model_name='serie',
            name='Producent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wideocollectorseader.producents'),
        ),
        migrations.AddField(
            model_name='serie',
            name='disLikes',
            field=models.ManyToManyField(blank=True, related_name='SerieDisLike', to='wideocollectorseader.DisLikess'),
        ),
        migrations.AddField(
            model_name='serie',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Serielikes', to='wideocollectorseader.Likes'),
        ),
        migrations.AddField(
            model_name='serie',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='SerieMovie', to='wideocollectorseader.Movie'),
        ),
        migrations.AddField(
            model_name='serie',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='SerieRating', to='wideocollectorseader.Rating'),
        ),
        migrations.AddField(
            model_name='serie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='serietags', to='wideocollectorseader.Tag'),
        ),
        migrations.AddField(
            model_name='serie',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='SerieViews', to='wideocollectorseader.Views'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wideocollectorseader.producents'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='MovieRating', to='wideocollectorseader.Rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wideocollectorseader.serie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='MovieStars', to='wideocollectorseader.Star'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Moviestags', to='wideocollectorseader.Tag'),
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='MovieViews', to='wideocollectorseader.Views'),
        ),
        migrations.AddField(
            model_name='producents',
            name='disLikes',
            field=models.ManyToManyField(blank=True, related_name='ProducentDisLike', to='wideocollectorseader.DisLikess'),
        ),
        migrations.AddField(
            model_name='producents',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Producentslikes', to='wideocollectorseader.Likes'),
        ),
        migrations.AddField(
            model_name='producents',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='ProducentsMovie', to='wideocollectorseader.Movie'),
        ),
        migrations.AddField(
            model_name='producents',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='ProducentRating', to='wideocollectorseader.Rating'),
        ),
        migrations.AddField(
            model_name='producents',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='ProducentsSerie', to='wideocollectorseader.Serie'),
        ),
        migrations.AddField(
            model_name='producents',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='producentstags', to='wideocollectorseader.Tag'),
        ),
        migrations.AddField(
            model_name='producents',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='ProducentsViews', to='wideocollectorseader.Views'),
        ),
    ]
