# Generated by Django 3.1.3 on 2022-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wideocollectorseader', '0002_auto_20220323_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='producents',
            name='years',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
