# Generated by Django 3.1.3 on 2022-01-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wideocollectorseader', '0002_auto_20220104_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producents',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
