# Generated by Django 3.1.3 on 2022-01-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wideocollectorseader', '0003_auto_20220104_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producents',
            name='banner',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
