# Generated by Django 3.1.3 on 2023-04-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wideocollectorseader', '0003_producents_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='back_cover',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='front_cover',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
