# Generated by Django 3.1.3 on 2023-04-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wideocollectorseader', '0004_auto_20230415_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='source',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
