# Generated by Django 3.1.3 on 2022-01-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wideocollectorseader', '0006_auto_20220104_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='producents',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
